# kompyle development environment

services:
  dev:
    build:
      context: .
      dockerfile: docker/dev.dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
